name: Automatically bump patch version

on:
  push:
    branches:
      - master

jobs:
  Autobump:
    uses: DanySK/workflows/.github/workflows/compute-version-and-create-release.yml@0.1.0-dev66
    with:
      update-version: patch
