name: Update changelog

on:
  push:
    branches:
      - '*'

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: DanySK/compute-changelog-action@master
        with:
          token: ${{ github.token }}
