on:
  push:
    branches:
      - '*'

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: DanySK/compute-changelog-action@${{ github.sha }}
        with:
          token: ${{ github.token }}
